create or replace TABLE EMPLOYEES (
	ID NUMBER(38,0) NOT NULL,
	LAST_NAME VARCHAR(50) COLLATE 'de',
	FIRST_NAME VARCHAR(50) COLLATE 'de',
	EMAIL VARCHAR(50) COLLATE 'de',
	AVATAR VARCHAR(250) COLLATE 'de',
	JOB_TITLE VARCHAR(50) COLLATE 'de',
	DEPARTMENT VARCHAR(50) COLLATE 'de',
	MANAGER_ID NUMBER(38,0),
	PHONE VARCHAR(25) COLLATE 'de',
	ADDRESS1 VARCHAR(150) COLLATE 'de',
	ADDRESS2 VARCHAR(150) COLLATE 'de',
	CITY VARCHAR(50) COLLATE 'de',
	STATE VARCHAR(50) COLLATE 'de',
	POSTAL_CODE VARCHAR(15) COLLATE 'de',
	COUNTRY VARCHAR(50) COLLATE 'de',
	CHANGE_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);

