create or replace TABLE ORDERS (
	ID NUMBER(38,0) NOT NULL,
	EMPLOYEE_ID NUMBER(38,0),
	CUSTOMER_ID NUMBER(38,0),
	ORDER_DATE TIMESTAMP_NTZ(9),
	SHIPPED_DATE TIMESTAMP_NTZ(9),
	SHIP_NAME VARCHAR(50) COLLATE 'de',
	SHIP_ADDRESS1 VARCHAR(150) COLLATE 'de',
	SHIP_ADDRESS2 VARCHAR(150) COLLATE 'de',
	SHIP_CITY VARCHAR(50) COLLATE 'de',
	SHIP_STATE VARCHAR(50) COLLATE 'de',
	SHIP_POSTAL_CODE VARCHAR(50) COLLATE 'de',
	SHIP_COUNTRY VARCHAR(50) COLLATE 'de',
	SHIPPING_FEE NUMBER(19,4) DEFAULT 0,
	PAYMENT_TYPE VARCHAR(50) COLLATE 'de',
	PAID_DATE TIMESTAMP_NTZ(9),
	ORDER_STATUS VARCHAR(25) COLLATE 'de',
	CHANGE_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);

