create or replace TABLE ORDER_DETAILS (
	ORDER_ID NUMBER(38,0) NOT NULL,
	PRODUCT_ID NUMBER(38,0) NOT NULL,
	QUANTITY NUMBER(18,4) NOT NULL DEFAULT 0,
	UNIT_PRICE NUMBER(19,4) DEFAULT 0,
	DISCOUNT FLOAT NOT NULL DEFAULT 0,
	ORDER_DETAIL_STATUS VARCHAR(25) COLLATE 'de',
	DATE_ALLOCATED TIMESTAMP_NTZ(9),
	CHANGE_DATE TIMESTAMP_NTZ(9),
	primary key (ORDER_ID, PRODUCT_ID)
);