create or replace TABLE PRODUCTS (
	ID NUMBER(38,0) NOT NULL,
	PRODUCT_CODE VARCHAR(25) COLLATE 'de',
	PRODUCT_NAME VARCHAR(50) COLLATE 'de',
	DESCRIPTION VARCHAR(250) COLLATE 'de',
	STANDARD_COST NUMBER(19,4) DEFAULT 0,
	LIST_PRICE NUMBER(19,4) NOT NULL DEFAULT 0,
	TARGET_LEVEL NUMBER(38,0),
	REORDER_LEVEL NUMBER(38,0),
	MINIMUM_REORDER_QUANTITY NUMBER(38,0),
	QUANTITY_PER_UNIT VARCHAR(50) COLLATE 'de',
	DISCONTINUED NUMBER(38,0) NOT NULL DEFAULT 0,
	CATEGORY VARCHAR(50) COLLATE 'de',
	CHANGE_DATE TIMESTAMP_NTZ(9),
	primary key (ID)
);
